# Domain configuration
domain: respondua.org

# Namespace where certificates will be stored
namespace: gateway

# ClusterIssuer to use
clusterIssuer: letsencrypt-prod

# Certificates to create
certificates:
  - name: wildcard-respondua-org
    secretName: wildcard-respondua-org-tls
    dnsNames:
      - "*.respondua.org"
      - "respondua.org"
