services:
  nginx: 
    restart: unless-stopped
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/development/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mysite/media
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on: 
      - volunteer
  volunteer:
    build: .
    container_name: volunteer
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mysite/media
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis  

  redis:
    # image: redis:7.2.0-alpine3.18
    container_name: redis
    build: ./redis
    ports:
      - '6379:6379'
    command: sh -c "./init.sh"
    privileged: true
    # command: ["redis-server", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru", "--daemonize", "yes"]
    hostname: redis    
    volumes:
      - redisdata:/data
      - /proc/sys:/host_proc/sys:ro
    cap_add:
      - SYS_ADMIN

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # depends_on:
    #   - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      # - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"

volumes:
  redisdata:
  static_volume:
  media_volume:
  grafana_data:
  loki_data:
  promtail_data:

