apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  # HTTP redirect to HTTPS
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
    tls:
      httpsRedirect: true
  # HTTPS
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.gateway.credentialName }}
    hosts:
    {{- range .Values.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
