apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: letsencrypt-external
  namespace: cert-manager
spec:
  hosts:
  - acme-v02.api.letsencrypt.org
  - acme-staging-v02.api.letsencrypt.org
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
