apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: s3-eu-central-1
  namespace: {{ .Values.gateway.namespace }}
spec:
  hosts:
    - respondua.s3.eu-central-1.amazonaws.com
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
    - number: 443
      name: https
      protocol: TLS
