apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: github-external
spec:
  hosts:
  - github.com
  - api.github.com
  - githubusercontent.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
