# Generated by Django 5.2.4 on 2025-07-29 22:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_user_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='teaser_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
