# Generated by Django 5.2.4 on 2025-08-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.IntegerField(help_text='В минимальных единицах валюты (коп/грн*100, PLN grosz)')),
                ('currency', models.CharField(default='pln', max_length=10)),
                ('payment_intent', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
