# Generated by Django 5.2.4 on 2025-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='В валюте (например, 77.00 PLN или 15.50 USD)', max_digits=10),
        ),
    ]
