# Generated by Django 5.2.4 on 2025-08-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='card_brand',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='funding',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
