apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.certEmail }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}-private-key

    {{- if .Values.clusterIssuer.staging.enabled }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}

    solvers:
      - dns01:
          route53:
            region: {{ .Values.route53.region }}
            {{- if .Values.route53.hostedZoneID }}
            hostedZoneID: {{ .Values.route53.hostedZoneID }}
            {{- end }}
            accessKeyIDSecretRef:
              name: {{ .Values.route53.accessKeyIDSecretRef.name }}
              key: {{ .Values.route53.accessKeyIDSecretRef.key }}
            secretAccessKeySecretRef:
              name: {{ .Values.route53.secretAccessKeySecretRef.name }}
              key: {{ .Values.route53.secretAccessKeySecretRef.key }}
